# Generated by Django 4.2.11 on 2024-06-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findtrip', '0003_auto_20240624_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtrip',
            old_name='bookoing_date',
            new_name='booking_date',
        ),
    ]
