# Generated by Django 4.2.11 on 2024-06-25 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posttrip', '0001_initial'),
        ('users', '0004_alter_cardetails_usercar_alter_userfiles_userfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findtrip', '0004_rename_bookoing_date_bookingtrip_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtrip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='bookingtrip',
            name='passengers',
        ),
        migrations.AddField(
            model_name='bookingtrip',
            name='passenger',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, related_name='booked_trips_as_passenger', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingtrip',
            name='trip',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='posttrip.tripdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingtrip',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_trip_car', to='users.cardetails'),
        ),
    ]
