# Generated by Django 4.2.11 on 2024-07-07 09:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posttrip', '0002_tripdetails_canceled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_cardetails_usercar_alter_userfiles_userfile'),
        ('findtrip', '0005_remove_bookingtrip_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(default=datetime.datetime(2024, 7, 7, 9, 33, 30, 700179, tzinfo=datetime.timezone.utc))),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews', to='posttrip.tripdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(default=datetime.datetime(2024, 7, 7, 9, 33, 30, 700179, tzinfo=datetime.timezone.utc))),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reviews_received', to='users.cardetails')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reviews', to='posttrip.tripdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
