# Generated by Django 4.2.11 on 2024-07-07 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('findtrip', '0006_driverreview_carreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreview',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='driverreview',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
