# Generated by Django 4.2.11 on 2024-04-01 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_cardetails_usercar_alter_userfiles_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingpoint', models.CharField(max_length=30)),
                ('endpoint', models.CharField(max_length=30)),
                ('departuredate', models.DateField()),
                ('departuretime', models.CharField(max_length=20)),
                ('luggagesize', models.CharField(max_length=20)),
                ('pets', models.CharField(max_length=5)),
                ('emptyseats', models.IntegerField(default=1)),
                ('kilometers', models.IntegerField()),
                ('seatprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripcar', to='users.cardetails')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripposted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
