# Generated by Django 4.2.11 on 2024-06-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posttrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
