# Generated by Django 4.2.11 on 2024-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posttrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='endpoint',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='startingpoint',
            field=models.CharField(max_length=50),
        ),
    ]
