# Generated by Django 4.2.11 on 2024-07-07 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherpages', '0002_alter_notifications_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 9, 38, 51, 816435, tzinfo=datetime.timezone.utc)),
        ),
    ]
