# Generated by Django 4.2.11 on 2024-07-07 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otherpages', '0003_alter_notifications_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
