# Generated by Django 4.2.11 on 2024-03-29 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='profilepicture'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='userfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='carimage')),
                ('image2', models.ImageField(null=True, upload_to='carimage')),
                ('image3', models.ImageField(null=True, upload_to='carimage')),
                ('carmodelname', models.CharField(max_length=20, null=True)),
                ('seatingcapacity', models.IntegerField(default=5, null=True)),
                ('usercar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
