# Generated by Django 4.2.11 on 2024-04-01 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profilepicture_alter_userfiles_userfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='usercar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usercar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='userfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
